sh_binary(
    name = "clang_tidy",
    srcs = ["run_clang_tidy.sh"],
    data = ["//:clang_tidy_config"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "status",
    srcs = ["status.sh"],
    visibility = ["//visibility:public"],
)
